apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-registry
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mvaldron-tenant/devfile-registry/devfile-registry@sha256:ec67e76927235cdf12f7de7a1423169e093d40eb22b99e4ed90ff3986aef3862
        name: devfile-registry
        resources: {}
status: {}
