apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devfile-registry
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-registry
    app.kubernetes.io/part-of: devfile-registry
  name: devfile-registry
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: oci-metrics
    port: 5001
    protocol: TCP
    targetPort: 5001
  - name: index-metrics
    port: 7071
    protocol: TCP
    targetPort: 7071
  selector:
    app: devfile-registry
    app.kubernetes.io/instance: devfile-registry
status:
  loadBalancer: {}
